server:
  port: 8091

logging:
  level:
    org.springframework: info

spring:
  application:
    name: imdb
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:imdb;DATABASE_TO_UPPER=false
    username: imdb
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: false
    database: h2
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
#    spring.sql.init.mode=always
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC
  h2:
    console:
      enabled: true
      path: /h2-console
